### ISSUE TITLE
Codecov has disappeared from Pypi preventing installation of trustee

### ISSUE THREAD

**Issue by V19Torrent** [asjacobs92/scikit-explain#2]
It looks like Trustee depends on codecov, and that module has been removed from Pypi's website. 

We can no longer install trustee with `pip3 install trustee`.

root@3d202edaa1c4:/emperor# python3 --version
Python 3.7.5

root@3d202edaa1c4:/emperor# pip3 install trustee
...
...
...
ERROR: Could not find a version that satisfies the requirement codecov>=2.0.15 (from rootpath) (from versions: none)
ERROR: No matching distribution found for codecov>=2.0.15

root@3d202edaa1c4:/emperor# pip3 install codecov
ERROR: Could not find a version that satisfies the requirement codecov (from versions: none)
ERROR: No matching distribution found for codecov

**Comment by asjacobs92** [comment]
Thanks for bringing this to our attention! I am working to solve this asap, and will likely release a new version with the fix soon!

**Comment by asjacobs92** [comment]
I just released a new build of `trustee`, version `1.1.2` that should solve the issue.

https://pypi.org/project/trustee/1.1.2/

I also updated the use cases to use the latest version of `trustee`.
Please let me know if that solves the issue so I can close it. 🙂

**Comment by V19Torrent** [comment]
Awesome thank you so much for your quick action!! I was in the middle of working on a class project for my Master's course, and that's when this inconvenient mishap happened. The installation seems to be working now!

There do seem to be some issues with building the Dockerfile (at least in the vpn use case directory) and running the image. I'll open an issue there for that.
